### ISSUE TITLE
Crack Hammer Recipe - Compatibility issue?

### ISSUE THREAD

**Issue by jcjudd01** [xStopho-Mods/Resource-Cracker#4]
trying to craft iron crack hammer, with correct ingredients and nothing shows up when I hit the Plus key to craft the item on the latest version of the mod from today

**Comment by Stein-N** [comment]
Hey what ModLoader you are using and what do you mean by pressing the Plus Key? Like the Fill Recipe Key from EMI/JEI/REI?

Are you using any other Mod beside Resource Cracker?

Edit:
I have tested all Mod Loader and the Recipes for all Crack hammer and the Dust Recipes work as intended and correctly:

**Comment by jcjudd01** [comment]
Fabric, on the plus key just the one with JEI to create the item once all the ingredients are loaded into the crafting table. Using about 80 other mods as well. must be an incompatibility between different mods then

**Comment by Stein-N** [comment]
Can you upload your latest logs, eventually there is an error inside that I can look into.

And what launcher do u use? Curseforge, Prism Launcher or MultiMC for example.

**Comment by jcjudd01** [comment]
just the standard launcher with fabric, will check for logs and send

**Comment by Stein-N** [comment]
Ok you don't need to upload your Logs, i was able to reproduce the Bug with only JEI and Resource Cracker installed

**Comment by Stein-N** [comment]
New Version will be available in 10 to 15 min
