### ISSUE TITLE
Just some missing names for Spring and Steel blocks on 1.21.4

### ISSUE THREAD

**Issue by BlocksRock-1006** [xStopho-Mods/Resource-Cracker#5]
Yes, the lava spring is the same sort of thing.
Yes, it's possible that it's a compat issue, but I don't think it's very likely.
![Screenshot 2024-12-07 120015](https://github.com/user-attachments/assets/db97d697-aaca-46bc-b6e4-85c92844bb69)
![Screenshot 2024-12-07 120030](https://github.com/user-attachments/assets/3961279b-7bf5-4103-b939-f3dc153e3806)

**Comment by Stein-N** [comment]
oh sry new version is published on modrinth and curseforge(available in 5-10 min)
