### ISSUE TITLE
New problem, this time with smelting Garlic

### ISSUE THREAD

**Issue by BlocksRock-1006** [xStopho-Mods/Resource-Cracker#6]
![Screenshot 2024-12-11 161112](https://github.com/user-attachments/assets/6624283e-b882-411d-88ff-35cde10bdffa)
'Nuff said.

**Comment by Stein-N** [comment]
new version is uploaded to curseforge, will be available in 5-10 min

**Comment by BlocksRock-1006** [comment]
Any chance of getting the new version on Modrinth?

**Comment by Stein-N** [comment]
Modrinth seems to have some problems currently i can't login or upload new files.
As soon i'm able to login i will upload the new version

**Comment by Stein-N** [comment]
if you don't want to download from Curseforge you can use this Datapack, this adds the correct Recipe.
Simply add it to the datapack folder inside your world and you are good to go.
[garlic_recipe_fix.zip](https://github.com/user-attachments/files/18114341/garlic_recipe_fix.zip)
